#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : KD and metal rich aerosols  # The title of the book. Will be placed in the left navbar.
author                      : Alejandro Fontal, Albert Navarro, Xavier Rodó  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : assets/logo.png # A path to the book logo

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/AlFontal/kd-metals-swc
  branch: main
html:
  google_analytics_id: G-DC18W62KP8
  use_repository_button: true
  use_issues_button: true
  favicon: assets/favicon.ico
  baseurl: 'https://alfontal.github.io/kd-metals-swc'
  comments:
    utterances: 
      repo: 'https://github.com/AlFontal/kd-metals-swc'
  extra_navbar: |
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <div>           
            <hr>
            <a href="https://helical-itn.github.io/">
            <img src="https://helical-itn.github.io/assets/institutional_logos/helical-logo.png" width=200px>
            </a>
            <p></p>
            <a href="https://www.isglobal.org/en/-/clima-y-salud">
            <img src="https://www.isglobal.org/isglobal-new-theme/assets/images/isglobal/logo-isglobal-en.png" width=200px>
            </a>

            </div>


sphinx:
  config:
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year
    
    html_baseurl: 'https://alfontal.github.io/kd-metals-swc/'
  
  extra_extensions:
   - sphinx_sitemap

